version: "3"
services:
  pccs.internal:
    image: ncl-sgx/pccs:1.8
    build:
      context: ./pccs
      args:
        DCAP_VERSION: DCAP_1.8
        CONFIG_FILE: ./config/production-0.json
        HTTPS_PORT: 8081
        HOST: 0.0.0.0
        API_KEY: ${API_KEY}
        ADMIN_TOKEN: ${ADMIN_TOKEN}
        USER_TOKEN: ${USER_TOKEN}
    networks:
      - pccs

  openenclave.base:
    image: ncl-sgx/openenclave:base-1.10
    build:
      context: ./openenclave
      args:
        OE_VERSION: v0.16.1
        PCCS_SERVER: pccs.internal:8081

  openenclave.dev:
    image: ncl-sgx/openenclave:dev-1.10
    build:
      context: ./development
      args:
        BASE: ncl-sgx/openenclave:base-1.10
        MBEDTLS_VERSION: 2.26.0
    depends_on:
      - openenclave.base

  openenclave.join:
    image: ncl-sgx/openenclave:join-1.10
    build:
      context: ./join
      args:
        BASE: ncl-sgx/openenclave:dev-1.10
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
    volumes:
      - /dev/sgx:/dev/sgx
      - /var/run/aesmd:/var/run/aesmd
      - ./ssh:/home/ubuntu/.ssh
    networks:
      - pccs
    depends_on:
      - openenclave.dev
      - pccs.internal

  openenclave.bmv2:
    image: ncl-sgx/openenclave:bmv2-1.10
    build:
      context: ./bmv2
      args:
        BASE: ncl-sgx/openenclave:dev-1.10
    privileged: true
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
    volumes:
      - /dev/sgx:/dev/sgx
      - /var/run/aesmd:/var/run/aesmd
      - ./ssh:/home/ubuntu/.ssh
    networks:
      - pccs
    depends_on:
      - openenclave.dev
      - pccs.internal

  openenclave.ctest:
    image: ncl-sgx/openenclave:ctest-1.10
    build:
      context: ./ctest
      args:
        BASE: ncl-sgx/openenclave:base-1.10
        OE_VERSION: v0.16.1
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
    volumes:
      - /dev/sgx:/dev/sgx
      - /var/run/aesmd:/var/run/aesmd
    networks:
      - pccs
    environment:
      OE_LOG_LEVEL: INFO
    depends_on:
      - openenclave.base
      - pccs.internal

networks:
  pccs:
