version: "3"
services:
  openenclave.base:
    extends:
      file: common-services.yml
      service: openenclave.base

  pccs.internal:
    extends:
      file: common-services.yml
      service: pccs.internal
    ports:
      - 8081
    networks:
      - pccs

  openenclave.dev:
    image: ncl-sgx/openenclave:dev-1.8
    build:
      context: ./development
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
    volumes:
      - /dev/sgx:/dev/sgx
      - /var/run/aesmd:/var/run/aesmd
    networks:
      - pccs
    environment:
      OE_LOG_LEVEL: INFO
    depends_on:
      - openenclave.base
      - pccs.internal

networks:
  pccs:
