version: "3"
services:
  pccs.internal:
    image: ncl-sgx/pccs:1.10
    build:
      context: ./pccs
      args:
        - DCAP_VERSION
        - CONFIG_TEMPLATE
        - HTTPS_PORT
        - HOST
        - API_KEY
        - ADMIN_TOKEN
        - USER_TOKEN
    networks:
      - pccs

  aems.internal:
    image: ncl-sgx/aems:2.14
    build:
      context: .
      dockerfile: Dockerfile.aesmd
      args:
        - PCCS_SERVER
    depends_on:
      - pccs.internal
    networks:
      - pccs
    volumes:
      - aesmd-socket:/var/run/aesmd

  openenclave.share:
    image: ncl-sgx/dev:share
    build:
      context: .
      dockerfile: Dockerfile.openencalve
      target: SHARE
      args:
        - PCCS_SERVER
        - MBEDTLS_VERSION
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
    environment:
      - SGX_AESM_ADDR=1
    hostname: ${HOSTNAME}-dev
    networks:
      - pccs
    volumes:
      - ./ssh:/home/ubuntu/.ssh
      - ./volume/intel:/home
      - /dev/sgx:/dev/sgx
      - aesmd-socket:/var/run/aesmd
    ports:
      - "22000:22"
    depends_on:
      - aems.internal

  # openenclave.bmv2:
  #   image: ncl-sgx/openenclave:bmv2-v0.17.1
  #   build:
  #     context: ./bmv2
  #     args:
  #       BASE: ncl-sgx/openenclave:dev-v0.17.1
  #   privileged: true
  #   devices:
  #     - /dev/sgx_enclave:/dev/sgx_enclave
  #     - /dev/sgx_provision:/dev/sgx_provision
  #   volumes:
  #     - /dev/sgx:/dev/sgx
  #     - /var/run/aesmd:/var/run/aesmd
  #     - ./ssh:/home/ubuntu/.ssh
  #   networks:
  #     - pccs
  #   depends_on:
  #     - openenclave.dev
  #     - pccs.internal

networks:
  pccs:

volumes:
  aesmd-socket:
